apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
  - imageName: guestbook
    workspace: ./
    docker:
      dockerfilePath: ./Dockerfile
  local: {}
deploy:
  kubectl:
    manifests:
    - ./kubernetes/*